### ISSUE TITLE
Update service to serve several MATSim networks

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees-server#1]
We want to be able to 

* [x] Dowload and load a list of mbtiles databases; for now we want to serve the Mount Alexander Shire network (already done), as well as the Surf Coast Shire network which is [here](https://cloudstor.aarnet.edu.au/plus/s/JK7STxWGKI2jNe4/download).

* [x] Serve the tiles for the different netwroks based on this scheme: `/tiles/:layer/:z/:x/:y.pbf` where layer might be `mount-alexander-shire` or `surf-coast-shire` for instance. 

We will add more regions as we go so set it up to accommodatet this.

**Comment by ayoung012** [comment]
This is done. As far as I can see the server is not being auto-deployed.

**Comment by ayoung012** [comment]
It has been auto-deployed, took a few mins
